// Mock data for development - Replace with real API calls to FastAPI + MongoDB

import { Product, Category } from '@/types/product';

export const mockCategories: Category[] = [
  {
    _id: '1',
    name: 'Roupas Femininas',
    slug: 'roupas-femininas',
    subcategories: ['Vestidos', 'Blusas', 'Calças', 'Saias', 'Jaquetas'],
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800',
  },
  {
    _id: '2',
    name: 'Roupas Masculinas',
    slug: 'roupas-masculinas',
    subcategories: ['Camisas', 'Camisetas', 'Calças', 'Jaquetas', 'Shorts'],
    image: 'https://images.unsplash.com/photo-1490114538077-0a7f8cb49891?w=800',
  },
  {
    _id: '3',
    name: 'Acessórios',
    slug: 'acessorios',
    subcategories: ['Bolsas', 'Sapatos', 'Joias', 'Óculos', 'Cintos'],
    image: 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800',
  },
];

export const mockProducts: Product[] = [
  {
    _id: '1',
    name: 'Vestido Floral Elegante',
    description: 'Vestido longo floral perfeito para ocasiões especiais. Tecido leve e confortável com estampa exclusiva.',
    price: 299.90,
    originalPrice: 399.90,
    category: 'Roupas Femininas',
    subcategory: 'Vestidos',
    brand: 'Eleganza',
    sizes: ['P', 'M', 'G', 'GG'],
    colors: [
      { name: 'Floral Rosa', hex: '#FFB6C1' },
      { name: 'Floral Azul', hex: '#87CEEB' },
    ],
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800',
    ],
    stock: 25,
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ['casual', 'elegante', 'verão'],
    rating: 4.5,
    reviewCount: 128,
  },
  {
    _id: '2',
    name: 'Camisa Social Slim Fit',
    description: 'Camisa social masculina corte slim fit. Tecido premium com tratamento anti-rugas.',
    price: 159.90,
    category: 'Roupas Masculinas',
    subcategory: 'Camisas',
    brand: 'Executive',
    sizes: ['P', 'M', 'G', 'GG', 'XG'],
    colors: [
      { name: 'Branco', hex: '#FFFFFF' },
      { name: 'Azul Marinho', hex: '#000080' },
      { name: 'Preto', hex: '#000000' },
    ],
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800',
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800',
    ],
    stock: 45,
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ['formal', 'trabalho', 'premium'],
    rating: 4.8,
    reviewCount: 256,
  },
  {
    _id: '3',
    name: 'Bolsa de Couro Premium',
    description: 'Bolsa de couro legítimo com acabamento artesanal. Design moderno e atemporal.',
    price: 549.90,
    originalPrice: 699.90,
    category: 'Acessórios',
    subcategory: 'Bolsas',
    brand: 'Luxe',
    sizes: ['Único'],
    colors: [
      { name: 'Marrom', hex: '#8B4513' },
      { name: 'Preto', hex: '#000000' },
      { name: 'Caramelo', hex: '#D2691E' },
    ],
    images: [
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800',
    ],
    stock: 15,
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ['luxo', 'couro', 'artesanal'],
    rating: 4.9,
    reviewCount: 89,
  },
  {
    _id: '4',
    name: 'Jaqueta Jeans Vintage',
    description: 'Jaqueta jeans com lavagem vintage. Estilo casual e versátil para todas as ocasiões.',
    price: 249.90,
    category: 'Roupas Femininas',
    subcategory: 'Jaquetas',
    brand: 'Urban Style',
    sizes: ['P', 'M', 'G'],
    colors: [
      { name: 'Azul Claro', hex: '#ADD8E6' },
      { name: 'Azul Escuro', hex: '#00008B' },
    ],
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800',
    ],
    stock: 30,
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ['casual', 'vintage', 'jeans'],
    rating: 4.3,
    reviewCount: 67,
  },
  {
    _id: '5',
    name: 'Tênis Esportivo Premium',
    description: 'Tênis esportivo com tecnologia de amortecimento avançada. Conforto e estilo para o dia a dia.',
    price: 399.90,
    category: 'Acessórios',
    subcategory: 'Sapatos',
    brand: 'SportMax',
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    colors: [
      { name: 'Branco', hex: '#FFFFFF' },
      { name: 'Preto', hex: '#000000' },
      { name: 'Vermelho', hex: '#FF0000' },
    ],
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
      'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800',
    ],
    stock: 60,
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ['esporte', 'conforto', 'casual'],
    rating: 4.7,
    reviewCount: 342,
  },
  {
    _id: '6',
    name: 'Calça Alfaiataria Feminina',
    description: 'Calça de alfaiataria com caimento perfeito. Ideal para ambiente corporativo.',
    price: 189.90,
    originalPrice: 249.90,
    category: 'Roupas Femininas',
    subcategory: 'Calças',
    brand: 'Eleganza',
    sizes: ['36', '38', '40', '42', '44'],
    colors: [
      { name: 'Preto', hex: '#000000' },
      { name: 'Cinza', hex: '#808080' },
      { name: 'Azul Marinho', hex: '#000080' },
    ],
    images: [
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800',
      'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800',
    ],
    stock: 40,
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ['formal', 'trabalho', 'elegante'],
    rating: 4.6,
    reviewCount: 145,
  },
  {
    _id: '7',
    name: 'Óculos de Sol Aviador',
    description: 'Óculos de sol estilo aviador com proteção UV400. Design clássico e atemporal.',
    price: 129.90,
    category: 'Acessórios',
    subcategory: 'Óculos',
    brand: 'SunStyle',
    sizes: ['Único'],
    colors: [
      { name: 'Dourado', hex: '#FFD700' },
      { name: 'Prata', hex: '#C0C0C0' },
      { name: 'Preto', hex: '#000000' },
    ],
    images: [
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800',
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800',
    ],
    stock: 80,
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ['acessório', 'proteção', 'estilo'],
    rating: 4.4,
    reviewCount: 203,
  },
  {
    _id: '8',
    name: 'Camiseta Básica Premium',
    description: 'Camiseta básica em algodão premium. Conforto e qualidade para o dia a dia.',
    price: 79.90,
    category: 'Roupas Masculinas',
    subcategory: 'Camisetas',
    brand: 'BasicWear',
    sizes: ['P', 'M', 'G', 'GG', 'XG'],
    colors: [
      { name: 'Branco', hex: '#FFFFFF' },
      { name: 'Preto', hex: '#000000' },
      { name: 'Cinza Mescla', hex: '#A9A9A9' },
      { name: 'Azul Marinho', hex: '#000080' },
    ],
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
    ],
    stock: 120,
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ['básico', 'casual', 'algodão'],
    rating: 4.5,
    reviewCount: 567,
  },
];
